services:
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    depends_on:
      - mysql
    command: sh -c "sleep 15s; uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000

  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_BASEURL=http://127.0.0.1:8000/books
    ports:
      - 3000:3000
